[package]
name = "game-def"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
enum-map = { version = "2.7.3", features = ["serde"] }
serde = "1.0.214"
serde_json = "1.0.132"
